### ISSUE TITLE
fix: handle TransactWriteError

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nshm-toshi-api#122]
In New DynamoDB we see very occasionally ...

diagnose and handle this ..

```
[ERROR]	2022-03-13T07:06:39.178Z	17f5404e-04c0-4802-bcba-80fd5a2fd04f	An error occurred while resolving field MutationRoot.create_automation_task
Traceback (most recent call last):
  File "/var/task/pynamodb/connection/base.py", line 1079, in transact_write_items
    return self.dispatch(TRANSACT_WRITE_ITEMS, operation_kwargs, settings)
  File "/var/task/pynamodb/connection/base.py", line 329, in dispatch
    data = self._make_api_call(operation_name, operation_kwargs, settings)
  File "/var/task/pynamodb/connection/base.py", line 440, in _make_api_call
    raise VerboseClientError(botocore_expected_format, operation_name, verbose_properties)
pynamodb.exceptions.VerboseClientError: An error occurred (TransactionCanceledException) on request (8EQIKU7483KU4RAH1VAERM7NLFVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (ToshiThingObject-TEST,ToshiIdentity-TEST) when calling the TransactWriteItems operation: Transaction cancelled, please refer cancellation reasons for specific reasons [ConditionalCheckFailed, ConditionalCheckFailed]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/graphql_api/data/base_data.py", line 177, in _write_object
    transaction.save(toshi_object)
  File "/var/task/pynamodb/transactions.py", line 31, in __exit__
    self._commit()
  File "/var/task/pynamodb/transactions.py", line 125, in _commit
    response = self._connection.transact_write_items(
  File "/var/task/pynamodb/connection/base.py", line 1081, in transact_write_items
    raise TransactWriteError("Failed to write transaction items", e)
pynamodb.exceptions.TransactWriteError: Failed to write transaction items

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/task/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/var/task/graphql_api/schema/custom/automation_task.py", line 104, in mutate
    task_result = get_data_manager().thing.create('AutomationTask', **input)
  File "/var/task/graphql_api/data/thing_data.py", line 42, in create
    self._write_object(next_id, self._prefix, body)
  File "/var/task/graphql_api/data/base_data.py", line 180, in _write_object
    logger.error(f'TransactWriteError.response {e.response}')
AttributeError: 'TransactWriteError' object has no attribute 'response'
```

**Comment by chrisbc** [comment]
examples:
**Inversion Runzi-automation-crustal_inversions-29**
 - https://console.aws.amazon.com/batch/home?region=us-east-1#jobs/detail/95630481-d025-4ce1-9039-8c8d1b0de690
 - https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fbatch$252Fjob/log-events/Fargate-runzi-opensha-JD$252Fdefault$252Fbfb0059db3dd48ca924303c98f461a86 (2022-03-13T20:06:39.284+13:00)
 - https://ap-southeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fnzshm22-toshi-api-test-app/log-events/2022$252F03$252F13$252F$255B$2524LATEST$255Df462fd5aa45e41979ece310ac96121a3$3FfilterPattern$3D (2022-03-13T07:06:39.178Z) see above

**Comment by chrisbc** [comment]
**Inversion Runzi-automation-crustal_inversions-20**
 - https://console.aws.amazon.com/batch/home?region=us-east-1#jobs/detail/49dbfa2f-6899-40ec-81d4-0776bbb482d5
 - https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fbatch$252Fjob/log-events/Fargate-runzi-opensha-JD$252Fdefault$252F3febab4bc2bc4442a62a9094adcc6d22 (last event)
 - https://ap-southeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fnzshm22-toshi-api-test-app/log-events/2022$252F03$252F13$252F$255B$2524LATEST$255D63e82de6c9c14f8495b27f13b520b4d7 (2022-03-13T20:05:49.544+13:00) see below

```
[ERROR]	2022-03-13T07:05:49.543Z	c5b5a324-3de1-46a7-80f2-14df86f167e3	An error occurred while resolving field MutationRoot.create_task_relation
Traceback (most recent call last):
  File "/var/task/pynamodb/connection/base.py", line 1079, in transact_write_items
    return self.dispatch(TRANSACT_WRITE_ITEMS, operation_kwargs, settings)
  File "/var/task/pynamodb/connection/base.py", line 329, in dispatch
    data = self._make_api_call(operation_name, operation_kwargs, settings)
  File "/var/task/pynamodb/connection/base.py", line 440, in _make_api_call
    raise VerboseClientError(botocore_expected_format, operation_name, verbose_properties)
pynamodb.exceptions.VerboseClientError: An error occurred (TransactionCanceledException) on request (84BJU4O5N4H18DI24HAQQSDHSRVV4KQNSO5AEMVJF66Q9ASUAAJG) on table (ToshiThingObject-TEST) when calling the TransactWriteItems operation: Transaction cancelled, please refer cancellation reasons for specific reasons [TransactionConflict]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/task/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/var/task/graphql_api/schema/task_task_relation.py", line 60, in mutate
    thing_relation = get_data_manager().thing_relation.create(parent_type, child_type, parent_id, child_id, **kwargs)
  File "/var/task/graphql_api/data/thing_relation_data.py", line 25, in create
    self._db_manager.thing.add_child_relation(thing_id=parent_id, relation_id=child_id, relation_clazz=child_clazz)
  File "/var/task/graphql_api/data/thing_data.py", line 149, in add_child_relation
    self.transact_update(thing_id, self._prefix, obj)
  File "/var/task/graphql_api/data/base_data.py", line 199, in transact_update
    transaction.update(
  File "/var/task/pynamodb/transactions.py", line 31, in __exit__
    self._commit()
  File "/var/task/pynamodb/transactions.py", line 125, in _commit
    response = self._connection.transact_write_items(
  File "/var/task/pynamodb/connection/base.py", line 1081, in transact_write_items
    raise TransactWriteError("Failed to write transaction items", e)
pynamodb.exceptions.TransactWriteError: Failed to write transaction items
```

**Comment by chrisbc** [comment]
New logging for **add_child_relation** using a 100/10 GT task (from runzi with INVERSION_SPOOFING) is able to reproduce integrity issue using local stack ....

using git commit e3002d3c7cdad40fe4d3e6b049c2a215b7866aa2

note 6 children is returned twice  -  one update has squashed another.

```
022-03-17 10:05:37,783 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1206 to children 1
2022-03-17 10:05:37,803 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1207 to children 2
2022-03-17 10:05:37,933 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1208 to children 3
2022-03-17 10:05:37,947 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1209 to children 4
2022-03-17 10:05:38,170 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1210 to children 5
2022-03-17 10:05:38,176 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1211 to children 6
2022-03-17 10:05:38,176 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1212 to children 6
2022-03-17 10:05:38,519 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1214 to children 8
2022-03-17 10:05:38,519 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1213 to children 7
2022-03-17 10:05:38,599 [INFO] graphql_api.data.thing_data: add_child_relation transaction OK: added: 1215 to children 9
```
