### ISSUE TITLE
Fix: get_general_task_subtasks for ScaledSolutions

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/nshm-toshi-api#268]
When calling `get_general_task_subtasks` for a GT that produced ScaledInversionSolutions, we get the following error:

```
Traceback (most recent call last):
  File "/home/chrisdc/NSHM/DEV/scripts/get_output_ids_and_meta.py", line 24, in <module>
    for id in output_ids:
  File "/home/chrisdc/NSHM/DEV/nzshm-runzi/runzi/automation/scaling/file_utils.py", line 12, in get_output_file_ids
    api_result = general_task_api.get_subtask_files(upstream_task_id)
  File "/home/chrisdc/NSHM/DEV/nzshm-runzi/runzi/automation/scaling/toshi_api/toshi_api.py", line 47, in get_subtask_files
    gt = self.get_general_task_subtasks(id)
  File "/home/chrisdc/NSHM/DEV/nzshm-runzi/runzi/automation/scaling/toshi_api/toshi_api.py", line 99, in get_general_task_subtasks
    executed = self.run_query(qry, input_variables)
  File "/home/chrisdc/.virtualenvs/test_oq_reports/lib/python3.8/site-packages/nshm_toshi_client/toshi_client_base.py", line 78, in run_query
    response = self._client.execute(gql_query, variable_values)
  File "/home/chrisdc/.virtualenvs/test_oq_reports/lib/python3.8/site-packages/gql/client.py", line 370, in execute
    return self.execute_sync(
  File "/home/chrisdc/.virtualenvs/test_oq_reports/lib/python3.8/site-packages/gql/client.py", line 188, in execute_sync
    return session.execute(
  File "/home/chrisdc/.virtualenvs/test_oq_reports/lib/python3.8/site-packages/gql/client.py", line 783, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': "object of type 'NoneType' has no len()"}
```

commenting out line 72 in `toshi_api.py` `swept_arguments` in the query fixes the problem

PROD GT example R2VuZXJhbFRhc2s6MTAzMDc1

**Comment by chrisdicaprio** [comment]
@chrisdicaprio needs to investigate and get query example to continue work

**Comment by chrisdicaprio** [comment]
can be handled gracefully as the response from the API is
```
{
  "errors": [
    {
      "message": "object of type 'NoneType' has no len()",
      "locations": [
        {
          "line": 5,
          "column": 19
        }
      ],
      "path": [
        "node",
        "swept_arguments"
      ]
    }
  ],
  "data": {
    "node": {
      "__typename": "GeneralTask",
      "swept_arguments": null
    }
  }
}
```
